location_names: 
  - L0
  - L1
  - L2
  - L3
  - L4
  - L5
L0_point: {
  x: 0.4,
  y: 0.4,
  z: 0.1,
}
L1_point: {
  x: 0.4,
  y: 0.0,
  z: 0.1,
}
L2_point: {
  x: 0.4,
  y: -0.4,
  z: 0.1,
}
L3_point: {
  x: -0.4,
  y: 0.4,
  z: 0.1,
}
L4_point: {
  x: -0.4,
  y: 0.0,
  z: 0.1,
}
L5_point: {
  x: -0.4,
  y: -0.4,
  z: 0.1,
}
location_orientation_types:
  - up
  - up
  - up
  - up
  - up
  - up
obj_group:
  - obj_1
  - obj_2
  - obj_3
init_obj_locations:
  - L0
  - L1
  - L2